### ISSUE TITLE
Task in autoupdate-RedHat.yml does not work on Rocky 9 

### ISSUE THREAD

**Issue by FH089** [geerlingguy/ansible-role-security#134]
Hi 

This task does not work on Rocky 9 and ansible 2.17.3

```YAML
- name: Configure autoupdates.
  lineinfile:
    dest: '{{ update_conf_path }}'
    regexp: '^apply_updates = .+'
    line: 'apply_updates = yes'
    mode: 0644
  when:
    - security_autoupdate_enabled
    - ansible_distribution_major_version | int in [7, 8]
``` 

by adding this it works

```diff
- - ansible_distribution_major_version | int in [7, 8]
+ - ansible_distribution_major_version | int in [7, 8, 9]
```
