### ISSUE TITLE
Missing fail2ban dependency on Debian

### ISSUE THREAD

**Issue by oltdaniel** [geerlingguy/ansible-role-security#140]
In the commit https://github.com/geerlingguy/ansible-role-security/commit/0b9a774f875ff3c175fc4f16a6d2b5b479d17e45 the `backend` for the SSH Jail for Fail2Ban on Debian 12 and higher is set to `systemd`. However, this requires an additional python package called `python3-systemd` in order to work (listed [here `fail2ban/fail2ban/README.md`](https://github.com/fail2ban/fail2ban/blob/b0d4eb07e5719a03c9eb0edf647cd0ff3272291e/README.md?plain=1#L44)). Currently, on very minimal Debian Default Setups, this causes the `fail2ban` service to fail on start.

Related Issue and PR: https://github.com/geerlingguy/ansible-role-security/issues/121 , https://github.com/geerlingguy/ansible-role-security/pull/122

My proposal for a fix would be introducing a new variable called `security_fail2ban_optional_dependencies`:

```yaml
security_fail2ban_optional_dependencies:
  - python3-systemd
```

Used by the following additional task at a good position:

```yaml
- name: Install fail2ban optional dependencies.
  ansible.builtin.package:
    name: "{{ security_fail2ban_optional_dependencies }}"
    state: present
  notify:
    - reload fail2ban
```

If the proposal meets your expectations, I'm happy to open a corresponding Pull Request.
