### ISSUE TITLE
How to make the `ansible_port` dynamic in a playbook including this role 

### ISSUE THREAD

**Issue by sphuber** [geerlingguy/ansible-role-security#77]
This role works great and I would like to use it, among other things, to change the default ssh port. The problem is, however, when I include this role in a playbook of multiple roles that sets up a machine from scratch, the playbook cannot be reused without changing the port. When setting the machine up for the first time, ansible _has_ to connect over port 22, but once the `security` role has run, the custom port should be used. This can of course be fixed by specifying `ansible_port` in the hosts file, for example, but this will then cause the very first run to fail. Is there a way that the playbook can be written such that it can always be used without having to change the port.

I cannot help but feel others using this role must have run into the same problem, but could not find anything in the old closed issues. Maybe I am just using this role incorrectly.

**Comment by robaczek** [comment]
I am currently looking for a solution to this and this gist looks promising: https://gist.github.com/triplepoint/1ad6c6060c0f12112403d98180bcf0b4

_Kind of necroposting, sorry._

**Comment by stephen304** [comment]
I also had this issue, I tried the task robaczek linked to and managed to get it to work like so:

```
- name: My play
  hosts: host_group
  gather_facts: false
  pre_tasks:
    - import_tasks: tasks/_sshd_port_juggling.yml
    - name: Gathering facts
      setup:
    - apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

```

The key for me was gather_facts: false followed by the `setup:` task to gather facts after sshd_port_juggling finished.

My hosts look like this:

```
      hosts:
        ln-1:
          ansible_host: x.x.x.x
          ansible_port: 1234
          security_ssh_port: 1234
          ansible_user: root
```
The sshd_port_juggling tasks tries 1234 first and falls back to 22, then the rest of your playbook runs as usual.
